=== AaronHer/IFCD0210/MF0491_3 CLIENTE/UF1841/E2/Esquema/Esquema_Equipo.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generado con XMLSpy v2019 sp1 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="entrenador">
		<xs:complexType>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="p"/>
				<xs:element ref="entrenador"/>
				<xs:element ref="nombre_entrenador"/>
				<xs:element ref="jugadores"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipo_de_futbol">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equipo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="img">
		<xs:complexType>
			<xs:attribute name="alt" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Central"/>
						<xs:enumeration value="Delantero Centro"/>
						<xs:enumeration value="Extremo Izquierdo"/>
						<xs:enumeration value="Extremo derecho"/>
						<xs:enumeration value="Lateral_Dch"/>
						<xs:enumeration value="Lateral_Izq"/>
						<xs:enumeration value="Mediocentro"/>
						<xs:enumeration value="Portero"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="src" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:anyURI">
						<xs:enumeration value="C:\Users\pc\Desktop\E2\Imagenes\01_TER-STEGEN-JOC"/>
						<xs:enumeration value="C:\Users\pc\Desktop\E2\Imagenes\02-SEMEDO-JOC"/>
						<xs:enumeration value="C:\Users\pc\Desktop\E2\Imagenes\03-PIQUE-JOC"/>
						<xs:enumeration value="C:\Users\pc\Desktop\E2\Imagenes\04-RAKITIC-JOC"/>
						<xs:enumeration value="C:\Users\pc\Desktop\E2\Imagenes\05-SERGIO-JOC"/>
						<xs:enumeration value="C:\Users\pc\Desktop\E2\Imagenes\07-COUTINHO-JOC"/>
						<xs:enumeration value="C:\Users\pc\Desktop\E2\Imagenes\09-SUAREZ-JOC"/>
						<xs:enumeration value="C:\Users\pc\Desktop\E2\Imagenes\10-MESSI-JOC"/>
						<xs:enumeration value="C:\Users\pc\Desktop\E2\Imagenes\18-JORDI-ALBA-JOC"/>
						<xs:enumeration value="C:\Users\pc\Desktop\E2\Imagenes\23-UMTITI-JOC"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="jugador">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="nacionalidad"/>
				<xs:element ref="img"/>
				<xs:sequence minOccurs="0">
					<xs:element ref="nombre"/>
					<xs:element ref="nacionalidad"/>
					<xs:element ref="img"/>
					<xs:element ref="nombre"/>
					<xs:element ref="nacionalidad"/>
					<xs:element ref="img"/>
					<xs:sequence minOccurs="0">
						<xs:element ref="nombre"/>
						<xs:element ref="nacionalidad"/>
						<xs:element ref="img"/>
					</xs:sequence>
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="posicion" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Centrocampista"/>
						<xs:enumeration value="Defensa"/>
						<xs:enumeration value="Delantero"/>
						<xs:enumeration value="Portero"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="jugadores">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="jugador" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nacionalidad">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Alemana"/>
				<xs:enumeration value="Argentíno"/>
				<xs:enumeration value="Brasileño"/>
				<xs:enumeration value="Croata"/>
				<xs:enumeration value="Española"/>
				<xs:enumeration value="Frances"/>
				<xs:enumeration value="Portugues"/>
				<xs:enumeration value="Uruguallo"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="nombre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="F.C.Barcelona"/>
				<xs:enumeration value="Gerard Piqué"/>
				<xs:enumeration value="Ivan Rakitic"/>
				<xs:enumeration value="Jordi Alba"/>
				<xs:enumeration value="Lionel Messi"/>
				<xs:enumeration value="Luis Suarez"/>
				<xs:enumeration value="Marc-André ter Stegen"/>
				<xs:enumeration value="Nélson Cabral Semedo"/>
				<xs:enumeration value="Ousmane Dembélé"/>
				<xs:enumeration value="Philippe Coutinho"/>
				<xs:enumeration value="Samuel Umtiti"/>
				<xs:enumeration value="Sergio Busquets"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="nombre_entrenador">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value=" Ernesto Valverde Tejedor "/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="p" type="xs:string"/>
</xs:schema>

=== AaronHer/IFCD0210/MF0491_3 CLIENTE/UF1841/E2/XML/E2_equipo.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipo_de_futbol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/pc/Desktop/E2/Esquema/Esquema_Equipo.xsd">
	<equipo>
		<nombre>F.C.Barcelona</nombre>
		<p> El Fútbol Club Barcelona (en catalán, Futbol Club Barcelona) es una entidad polideportiva de Barcelona (España). Fue fundado como club de fútbol el 29 de noviembre de 1899</p>
		<entrenador/>
		<nombre_entrenador> Ernesto Valverde Tejedor </nombre_entrenador>
		<jugadores>
			<!-- Este es el equipo Titular-->
			<jugador posicion="Portero">
				<nombre>Marc-André ter Stegen</nombre>
				<nacionalidad>Alemana</nacionalidad>
				<img alt="Portero" src="C:\Users\pc\Desktop\E2\Imagenes\01_TER-STEGEN-JOC"/>
			</jugador>
			<jugador posicion="Defensa">
				<nombre>Jordi Alba</nombre>
				<nacionalidad>Española</nacionalidad>
				<img alt="Lateral_Izq" src="C:\Users\pc\Desktop\E2\Imagenes\18-JORDI-ALBA-JOC"/>
				<nombre>Gerard Piqué</nombre>
				<nacionalidad>Española</nacionalidad>
				<img alt="Central" src="C:\Users\pc\Desktop\E2\Imagenes\03-PIQUE-JOC"/>
				<nombre>Samuel Umtiti</nombre>
				<nacionalidad>Frances</nacionalidad>
				<img alt="Central" src="C:\Users\pc\Desktop\E2\Imagenes\23-UMTITI-JOC"/>
				<nombre>Nélson Cabral Semedo</nombre>
				<nacionalidad>Portugues</nacionalidad>
				<img alt="Lateral_Dch" src="C:\Users\pc\Desktop\E2\Imagenes\02-SEMEDO-JOC"/>
			</jugador>
			<jugador posicion="Centrocampista">
				<nombre>Ivan Rakitic</nombre>
				<nacionalidad>Croata</nacionalidad>
				<img alt="Mediocentro" src="C:\Users\pc\Desktop\E2\Imagenes\04-RAKITIC-JOC"/>
				<nombre>Sergio Busquets</nombre>
				<nacionalidad>Española</nacionalidad>
				<img alt="Mediocentro" src="C:\Users\pc\Desktop\E2\Imagenes\05-SERGIO-JOC"/>
				<nombre>Philippe Coutinho</nombre>
				<nacionalidad>Brasileño</nacionalidad>
				<img alt="Mediocentro" src="C:\Users\pc\Desktop\E2\Imagenes\07-COUTINHO-JOC"/>
			</jugador>
			<jugador posicion="Delantero">
				<nombre>Lionel Messi</nombre>
				<nacionalidad>Argentíno</nacionalidad>
				<img alt="Extremo derecho" src="C:\Users\pc\Desktop\E2\Imagenes\10-MESSI-JOC"/>
				<nombre>Luis Suarez</nombre>
				<nacionalidad>Uruguallo</nacionalidad>
				<img alt="Delantero Centro" src="C:\Users\pc\Desktop\E2\Imagenes\09-SUAREZ-JOC"/>
				<nombre>Ousmane Dembélé</nombre>
				<nacionalidad>Frances</nacionalidad>
				<img alt="Extremo Izquierdo" src="C:\Users\pc\Desktop\E2\Imagenes\07-COUTINHO-JOC"/>
			</jugador>
		</jugadores>
	</equipo>
</equipo_de_futbol>
